name: hebrewbooks
version: 1.0.0+1
publish_to: none
description: Mobile interface to provide access to HebrewBooks.org
environment: 
  sdk: '>=3.1.0 <4.0.0'
dependencies: 
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^1.1.0
  material_color_utilities: ^0.5.0
  permission_handler: ^11.0.1
  provider: ^6.1.1
  pubspec_dependency_sorter: ^1.0.4
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_pdfviewer: ^24.1.47
dev_dependencies: 
  flutter_lints: ^3.0.2
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
flutter: 
  assets: 
    - assets/images/logo.png
  fonts: 
    - 
      family: icomoon
      fonts: 
        - 
          asset: assets/fonts/icomoon.ttf
  uses-material-design: true
